version: '2'
services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./web:/var/www/html/web
      - /var/www/html/vendor
      - /var/www/html/web/core
      - /var/www/html/web/libraries
      - /var/www/html/web/sites/default/files
      - /var/www/html/web/sites/default/files/styles
      - /var/www/html/web/sites/default/sync
      - /var/www/html/web/modules/contrib
      - /var/www/html/web/profiles/contrib
      - /var/www/html/web/themes/contrib
      - /var/www/html/web/drush/contrib
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ADDR: db
    restart: always

  db:
    image: mysql:8
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    restart: always
